import fs from 'fs'

const getWritableStream = (targetFile) => {
    if (targetFile === '-') {
        return process.stdout
    }
    return fs.createWriteStream(targetFile)
}

const writeJS = (exported, targetFile) => {
    return new Promise((resolve, reject) => {
        const stream = getWritableStream(targetFile)
        const json = JSON.stringify(exported, null,'\t')

        if (!stream.write(`### Generated by preamp
### Any changes are likely to be overwritten

const awsExports = ${json}

export default awsExports
`)) {
            reject('stream.write failed')
        }

        stream.end()
        stream.on("finish", () => { resolve(); });
        stream.on("error", reject);
      });
    
    return 
}

export {
    writeJS
}
